services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:10000"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/srv
      - ./favicon.ico:/srv/favicon.ico
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
